### ISSUE TITLE
Proxy?

### ISSUE THREAD

**Issue by bsideup** [theturtle32/AS3WebSocket#10]
Does this lib supports working under proxy?

**Comment by ykrkn** [comment]
I don`t think so. Flash player sends only HTTP/S requests through the browser and in this case FP works with proxy ok. But in this library used a raw socket connection. This is a reason.

**Comment by theturtle32** [comment]
No.  Flash player does not use browser proxy settings for raw socket connections, unfortunately, and nothing can be done about that.
