### ISSUE TITLE
Example for connecting to Socket.IO 0.9.x

### ISSUE THREAD

**Issue by nestradaOBS** [theturtle32/AS3WebSocket#11]
Hello,

I'm unable to get a working example for interfacing with socket.io/engine.io.. Is there a working example somewhere? I've tried many things, but transport errors, missing protocols and destroyed upgrades are all I came up with...

Nicolas

**Comment by theturtle32** [comment]
Socket.IO uses websocket as an option for the underlying transport, but it defines it's own protocol on top of that.  its not pure websocket.  AS3WebSocket is a raw websocket library, so you'd have to implement the socket.io parts on top of that yourself.  It's not designed to interoperate with socket.io out of the box.

Brian
