### ISSUE TITLE
enableDeflateStream error

### ISSUE THREAD

**Issue by alikim-com** [theturtle32/AS3WebSocket#12]
This line does not compile

websocket.enableDeflateStream = true;

1119: Access of possibly undefined property enableDeflateStream through a reference with static type com.worlize.websocket:WebSocket.

There is no such variable in the class, is that how it's meant to be?

**Comment by theturtle32** [comment]
The example is out of date.   The deflate-stream extension was abandoned by the IETF working group, so it was removed from the code.
