### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by alikim-com** [theturtle32/AS3WebSocket#13]
I'm trying to execute this part of the example:

websocket = new WebSocket("wss://echo.websocket.org", "*", "my-chat-protocol");
// websocket.enableDeflateStream = true;
websocket.addEventListener(WebSocketEvent.CLOSED, handleWebSocketClosed);
websocket.addEventListener(WebSocketEvent.OPEN, handleWebSocketOpen);
websocket.addEventListener(WebSocketEvent.MESSAGE, handleWebSocketMessage);
websocket.addEventListener(WebSocketErrorEvent.CONNECTION_FAIL, handleConnectionFail);
websocket.connect();

and I get an error:
Connection Failure: The server can not respond in any of our requested protocols
Disconnected

and in the trace output I have:
I DONT KNOW HOW TO HANDLE DER stuff of TYPE 12

Do you know what the problem might be?

**Comment by theturtle32** [comment]
the deflate stream stuff is old and has been removed.  I apologize if I forgot to update the example.  The deflate stream extension was abandoned by the working group, to be replaced with some more robust, more flexible compression extensions.

Your error is that you're requesting "my-chat-protocol" and your server is not affirming that it supports "my-chat-protocol"

Try removing "my-chat-protocol" and replacing it with null in the constructor.

**Comment by theturtle32** [comment]
Also, you can ignore the warning about "DER stuff of TYPE 12"

That's from the TLS library that AS3WebSocket uses to make encrypted connections.  It's not a 100% complete implementation, but it will work even though not all DER packets are handled.
