### ISSUE TITLE
SHA1 cannot hash correctly

### ISSUE THREAD

**Issue by elct9620** [theturtle32/AS3WebSocket#15]
I using AS3WebSocket to connect socket.io server (ver 0.9+)
And I cannot connect my server, but when I change SHA1 library like #1 suggest, it work correctly.

I also try add `as3crypto` and use its' SHA1 library, and it also work correctly.

**Comment by bmezhibovskiy** [comment]
I had the same problem with socket.io, and it was solved by my answer in #16...

**Comment by elct9620** [comment]
My finally solution is fork and change some code like this:
https://github.com/elct9620/AS3WebSocket/commit/00165fb0862bb7c2db1be788fc11be44cd20b4f2
