### ISSUE TITLE
Any plans to update to the final RFC6455 spec?

### ISSUE THREAD

**Issue by rejemy** [theturtle32/AS3WebSocket#2]
Don't want to nag, just curious if it's going to happen.

**Comment by theturtle32** [comment]
Yeah, I haven't gotten around to it because I've had a lot of other things
on my plate and there wasn't a ton that changed.  A pull-request would be
welcome, of course. ;-)

Brian

On Mon, Apr 9, 2012 at 4:57 PM, rejemy <
reply@reply.github.com

**Comment by rejemy** [comment]
In that case I'll try to take a detailed read through the spec diffs and see if I can put something together. I have long term plans for WebSockets in Actionscript, so it wouldn't hurt for me to be familiar with it anyway. Thanks for the update.

Jeremy

**Comment by theturtle32** [comment]
Awesome!  The changes aren't significant, mostly having to do with the opening handshake and a few new connection close codes.

**Comment by theturtle32** [comment]
Closed by pull request #3
