### ISSUE TITLE
Connecting to latest socketIO server works, but I get disconnected immediately

### ISSUE THREAD

**Issue by jBachalo** [theturtle32/AS3WebSocket#24]
I get a connected message when connecting to a socketIO server but then an immediate disconnect. 
Any suggestions? This is my complete message

```
Connecting to 192.168.4.134 on port 3000
Socket Connected
GET / HTTP/1.1
Host: 192.168.4.134:3000
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: ZnyGKnse5Tsdr6znXQKGSA==
Origin: *
Sec-WebSocket-Version: 13
Sec-WebSocket-Protocol: lws-mirror-protocol

Socket Disconnected
Websocket closed.
```

**Comment by theturtle32** [comment]
WebSockets and Socket.IO are not the same thing.  Socket.IO uses WebSockets as one possible transport medium, but also defines its own protocols on top.  While AS3WebSocket could be used as the WebSocket portion of a full Socket.IO client, you will have to implement the rest of the Socket.IO protocol also.

If you just want to connect flash to a server using WebSockets, skip Socket.IO and just use a plain WebSocket library, such as my WebSocket-Node library, instead.

Brian
