### ISSUE TITLE
Deflate stream

### ISSUE THREAD

**Issue by natami** [theturtle32/AS3WebSocket#25]
Is Deflate supported in the main branch?

**Comment by theturtle32** [comment]
No. It was at one time but the deflate stream was scrapped by the standards body before being ratified. There is a per-message deflate extension now, but I haven't implemented support for it and it hasn't quite been ratified yet either... It's still a draft spec as far as I am aware.

**Comment by natami** [comment]
Looks like it's implemented by the spring-framework:
Server: Apache-Coyote/1.1
Upgrade: websocket
Connection: upgrade
Sec-WebSocket-Accept: 6zn7dqte7uk2J3LG0ju+CGGfx7Q=
Sec-WebSocket-Extensions: permessage-deflate;client_max_window_bits=15
Date: Wed, 17 Jun 2015 04:53:36 GMT

**Comment by theturtle32** [comment]
It would be reasonable to implement support for the per-message deflate extension, but unfortunately I don't have the availability to work on it any time soon.

However, If you or someone else would like to implement support and send a pull request, I'd be happy to review and merge it.
