### ISSUE TITLE
Cannot send Ping Frame

### ISSUE THREAD

**Issue by zzzhr** [theturtle32/AS3WebSocket#6]
When use ws.ping(),A null pointer error occurred.

**Comment by theturtle32** [comment]
I haven't experienced this problem, but I took the opportunity to add events for ping and pong frames received, and to extend the API to allow you to optionally include a ping payload.  Go ahead and try it again.

**Comment by zzzhr** [comment]
It still happends.

**Comment by zzzhr** [comment]
In WebsocketFrame class,Send() function, if the Frame to send is an ping frame,the 'data' (defined in line168) would not be initized.
My soludion is add this in line 228:
data = new ByteArray();

It works fine:)

**Comment by theturtle32** [comment]
Ah good catch.  I was testing after my changes by including a payload to the call to ping(), i.e.:

var data:ByteArray = new ByteArray();
data.writeMultiByte("some data", "utf-8");
websocket.ping(data);

**Comment by theturtle32** [comment]
Just committed the fix and uploaded a new .swc and .air file to the Downloads section.
