### ISSUE TITLE
Need help on connection with AutoBahn|Python

### ISSUE THREAD

**Issue by Chetchaiyan** [theturtle32/AS3WebSocket#9]
Dear sir,

I'm setup websocket server by using AutoBahn|Python on Amazon EC2 successfully connected to Javascript websocket.

However, I'm facing the problem on connecting to AS3WebSocket.

When I test the AS3 project as debug from FlashDevelop the WebSocketErrorEvent.CONNETION_FAIL Occur with following text

<i>An HTTP response code other than 101 was received. Actual Response Code: 400 missing port in HTTP Host header '54.251.48.207' and server runs on non-standard port 10001 (wss=False)</i>

When I run the project on web browser, WebsocketEvent.CLOSED occur without WebSocketErrorEvent.CONNECTION_FAIL
same as when I upload the project to Amazon EC2.

I'm not good in Networking background, so Please guide me through out the problem, Please.

Best Regards, 
Chet Chetchaiyan

**Comment by theturtle32** [comment]
I think you've stumbled upon a bug in my code.  The code does not send the port as part of the host header.

**Comment by theturtle32** [comment]
Just checked in a fix for this.  Uploading new SWC files to the downloads section now.. stand by.

**Comment by theturtle32** [comment]
The new compiled SWC is now available in the main downloads section at https://github.com/Worlize/AS3WebSocket/downloads

I'm going to go ahead and close this issue.  Let me know if this works for you, and if not, re-open this issue or create another one.  Thanks again for finding this!

**Comment by theturtle32** [comment]
@Chetchaiyan can you confirm that this fix solves your issue?  Thanks!
